### ISSUE TITLE
Phone not returning GPS coordinates

### ISSUE THREAD

**Issue by Br1tt21** [nickfox/GpsTracker#107]
When I go to to https://www.websmithing.com/gpstracker/updatelocation.php, it always returns -1 on my phone and laptop. I filled in that address in the app to test, and I'm not appearing on the map. Am I doing something wrong?

**Comment by brentfraser** [comment]
I think Nick considers this project to be archived and he may not be monitoring it anymore, but I'll try to help.

It looks like websmithing.com is no longer operational.  It was a running instance of the server-side code included in this project.  you could try setting up your own web server instead of using websmithing.com.

**Comment by nickfox** [comment]
Hey Brent, actually I'm here and I'm working on bringing this back to life.
websmithing.com is currently getting its ubuntu updated. Hopefully will be
back up in a couple of hours.

This may be the reason why he's getting the -1.

n

**Comment by brentfraser** [comment]
Cool!

**Comment by nickfox** [comment]
Ok, can you try it again now. websmithing.com is working again.

n

**Comment by Br1tt21** [comment]
Hi, cool that you revived it! I got it up and running now on my own webserver, thanks a lot.
